apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: argo-test
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/n-barnes/argo-test
---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: argo-test
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: argo-test
  targetNamespace: argo-repo-test
 ---
 
apiVersion: source.toolkit.fluxcd.io/v1beta2 
kind: HelmRepository
metadata:
  name: application-helm
  namespace: flux-system
spec: 
  ref:
    branch: main
  interval: 30s
  url: https://github.com/n-barnes/fluxcd-application-repo
 ---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: application-helm
  namespace: flux-system
spec:
  prune: true
  interval: 30s
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: HelmRepository
        name: application-helm
        namespace: flux-system
      version: 0.1.0
  
