apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: argo-test
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/n-barnes/argo-test
---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: argo-test
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: afgo-test
  targetNamespace: argo-repo-test
  
